services:
  jupyterhub:
    build: .
    ports:
      - "12000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_NOTEBOOK_IMAGE=jupyter/base-notebook
      - DOCKER_NETWORK_NAME=tljh_jupyterhub-network
    networks:
      - jupyterhub-network

networks:
  jupyterhub-network:
    driver: bridge
